[project]
name = "streamlit-demo"
version = "0.1.0"
description = "Streamlit demonstration example"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "streamlit>=1.51.0",
]
